version: '3'

services:
  forecasts:
    network_mode: "host"
    container_name: forecasts
    hostname: forecasts
    environment:
      - "ASPNETCORE_URLS=https://+:44330"
    env_file:
      - ./docker-hostmode.env
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./
      dockerfile: ./WeatherForecast/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: local/forecasts

  luckynumbers:
    network_mode: "host"
    container_name: luckynumbers
    hostname: luckynumbers
    environment:
      - "ASPNETCORE_URLS=https://+:44331"
    env_file:
      - ./docker-hostmode.env
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./
      dockerfile: ./LucyNumbers/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: local/luckynumbers

  sql:
    network_mode: "host"
    container_name: sql
    hostname: sql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: 'TtprstF68'
    image: mcr.microsoft.com/mssql/server:2019-latest
