version: '3'

services:
  forecasts:
    network_mode: "host"
    container_name: forecasts
    hostname: forecasts
    environment:
      - "ASPNETCORE_URLS=https://0.0.0.0:44330;http://0.0.0.0:5023"
    env_file:
      - ./docker-hostmode.env
    expose:
      - "5023/tcp"
      - "44330/tcp"
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./
      dockerfile: ./WeatherForecast/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: local/forecasts

  luckynumbers:
    network_mode: "host"
    container_name: luckynumbers
    hostname: luckynumbers
    environment:
      - "ASPNETCORE_URLS=https://0.0.0.0:44331;http://0.0.0.0:5136"
    # These do not work, because bind to IPv6, but host mode requires IPv4
    # see https://docs.docker.com/network/drivers/host/#limitations
    #  - "ASPNETCORE_URLS=https://+:44331"
    #  - "ASPNETCORE_HTTP_PORTS=5136"
    #  - "ASPNETCORE_HTTPS_PORTS=44331"
    env_file:
      - ./docker-hostmode.env
    expose:
      - "5136/tcp"
      - "44331/tcp"
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./
      dockerfile: ./LuckyNumbers/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: local/luckynumbers

  sql:
    network_mode: "host"
    container_name: sql
    hostname: sql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: '${MSSQL_SA_PASSWORD}'
    image: mcr.microsoft.com/mssql/server:2019-latest
