version: '3'

services:
  forecasts:
    # using bridge mode, but with custom network, created by docker compose
    # so that we can use hostnames for container-to-container communication    
    #network_mode: "bridge"
    container_name: forecasts
    hostname: forecasts
    env_file:
      - ./docker.env
      - ./docker.env.override
    ports:
      - "45678:8080"  # http
      - "44330:4433"  # https
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./
      dockerfile: ./WeatherForecast/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: local/forecasts

  luckynumbers:
    #network_mode: "bridge"
    container_name: luckynumbers
    hostname: luckynumbers
    env_file:
      - ./docker.env
      - ./docker.env.override
    ports:
      - "45679:8080"  # http
      - "44331:4433"  # https
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: ./
      dockerfile: ./LuckyNumbers/Dockerfile
      args:
        BUILD_CONFIGURATION: Release
    image: local/luckynumbers

  sql:
    container_name: sql
    hostname: sql
    environment:
      ACCEPT_EULA: 'Y'
      MSSQL_SA_PASSWORD: '${MSSQL_SA_PASSWORD}'
    ports:
      - "14330:1433"
    image: mcr.microsoft.com/mssql/server:2019-latest
